apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops
  labels:
    app: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
        - name: mlops
          image: 412717959834.dkr.ecr.us-east-1.amazonaws.com/mlops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8005